sudo: required
language: python

matrix:
    include:
        - python: "3.8"
          os: linux
          dist: focal
        - python: "3.9-dev"
          os: linux
          dist: focal

addons:
  apt:
    packages:
    - libattr1-dev
    - pkg-config
    - gcc
    - ninja-build
    - meson
    - python3-sphinx
    - cython3
    - libfuse3-dev
    - fuse3
install: test/travis-install.sh
script: test/travis-test.sh
